#!/bin/bash

# Based on:
#   http://docs.ceph.com/docs/jewel/start/quick-start-preflight/

ceph_release="infernalis"
ceph_deploy_user="cephadmin"
ceph_deploy_pass="admin_pass"
ceph_nodes=("ceph0" "ceph1" "ceph2")

##############
# Admin Node #
##############

if [[ "x${cephadmin}" == 'xtrue' ]]; then
  # Add repo and install ceph-deploy
  wget -q -O- 'https://download.ceph.com/keys/release.asc' | sudo apt-key add -
  echo "deb http://download.ceph.com/debian-${ceph_release}/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/ceph.list
  sudo apt-get update
  sudo apt-get install --assume-yes ceph-deploy sshpass
fi

#############
# Ceph Node #
#############

# Recommended packages
sudo apt-get install --assume-yes ntp

# Create user
sudo useradd -d "/home/${ceph_deploy_user}" -m "${ceph_deploy_user}"
echo "${ceph_deploy_user}:${ceph_deploy_pass}" | sudo chpasswd

# Configure sudo
echo "${ceph_deploy_user} ALL = (root) NOPASSWD:ALL" | sudo tee /etc/sudoers.d/${ceph_deploy_user}
sudo chmod 0440 /etc/sudoers.d/${ceph_deploy_user}


##############
# Admin Node #
##############

if [[ "x${cephadmin}" == 'xtrue' ]]; then
  # Create Keys and Copy to Nodes
  ssh_identity_file="/home/${ceph_deploy_user}/.ssh/identity"
  ssh_config="/home/${ceph_deploy_user}/.ssh/config"

  sudo -u "${ceph_deploy_user}" -i -- bash -c "echo -e 'n\n'|ssh-keygen -b 4096 -N '' -f '${ssh_identity_file}'"
  echo

  sudo -u "${ceph_deploy_user}" -i -- bash -c "echo '# Auto-generated by Ceph Preflight script' > ${ssh_config}"
  sudo -u "${ceph_deploy_user}" -i -- bash -c "echo 'IdentityFile ${ssh_identity_file}' >> ${ssh_config}"
  sudo -u "${ceph_deploy_user}" -i -- bash -c "echo 'HashKnownHosts no' >> ${ssh_config}"

  for node in "${ceph_nodes[@]}"; do
    sudo -u "${ceph_deploy_user}" -i -- bash -c "sshpass -p'${ceph_deploy_pass}' ssh-copy-id -o StrictHostKeyChecking=no -i '${ssh_identity_file}' '${ceph_deploy_user}@${node}'"
    sudo -u "${ceph_deploy_user}" -i -- bash -c "echo -e 'Host ${node}' >> ${ssh_config}"
    sudo -u "${ceph_deploy_user}" -i -- bash -c "echo -e '  Hostname ${node}' >> ${ssh_config}"
    sudo -u "${ceph_deploy_user}" -i -- bash -c "echo -e '  User ${ceph_deploy_user}' >> ${ssh_config}"
  done

fi


